//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopHoaTuoi.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public int id { get; set; }
        public Nullable<int> mahd { get; set; }
        public Nullable<int> mahoa { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<decimal> tongtien { get; set; }
    
        public virtual HOA HOA { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
