//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopHoaTuoi.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAPHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUNHAPHOA()
        {
            this.CT_PHIEUNHAPHOA = new HashSet<CT_PHIEUNHAPHOA>();
        }
    
        public int mapnh { get; set; }
        public Nullable<int> mancc { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUNHAPHOA> CT_PHIEUNHAPHOA { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
